packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  /: true
  '@': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  a: true
  c: true
  e: true
  esbuild: true
  i: true
  l: true
  m: true
  n: true
  p: true
  prisma: true
  r: true
  s: true
  t: true
