services:
  - type: web
    name: homeflux-api
    runtime: node
    region: frankfurt

    buildCommand: npm install -g pnpm@10.32.1 --force && pnpm install --no-frozen-lockfile && pnpm --filter @homeflux/api run build

    startCommand: node apps/api/dist/server.js

    envVars:
      - key: NODE_VERSION
        value: "20.18.1"
      - key: NODE_ENV
        value: production